# title: Petit test
# description: Description du site petit test

# google_analytics:
# theme: jekyll-theme-cayman
# remote_theme: pages-themes/cayman@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one

title: CANISLUPA
description: Ã‰duque et balade ton chien
# show_downloads: true
# url: https://mon-domaine.fr        # ou https://user.github.io/mon-repo
# baseurl: "/petit-test-rapiid"
lang: fr
# timezone: Europe/Paris

author:
  name: canislupa
  # email: moi@example.com
  # url: https://mon-domaine.fr/a-propos

logo: /assets/images/logo_canislupa.png

# social:
#   name: Mon Site
#   links:
#     - https://github.com/metalbrackets
#     - https://www.linkedin.com/in/mon-profil/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

exclude:
  - docs
# permalink: /:categories/:title/
