url: https://canislupa.fr
baseurl: ""
lang: fr

title: CANISLUPA
description: Ã‰duque et balade ton chien
logo: /assets/images/logo_canislupa.png
banner: /assets/images/banner-1200x630.jpg

social:
  name: CANISLUPA
  links:
    - "https://www.facebook.com/canislupaeducationcanine"
    - "https://www.instagram.com/mary_canislupa/"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
# permalink: /:categories/:title/

defaults:
  - scope:
      path: ""
    values:
      lang: fr
      banner: /assets/images/banner-1200x630.jpg # image pour SEO partage
author:
  name: canislupa
  # email: moi@example.com
  # url: https://mon-domaine.fr/a-propos
# show_downloads: true

# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one

